language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image='rails'

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - docker build -t "$image:onbuild" onbuild

after_script:
  - docker images

# vim:set et ts=2 sw=2:
